@host=http://localhost:5051

GET {{host}}/dinners 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNmU5NWQ3My0wYTUxLTQ0OWUtODZlZC1kMTY1NmYxYzFkZjgiLCJnaXZlbl9uYW1lIjoiQWRlbSIsImZhbWlseV9uYW1lIjoiYWRlIiwianRpIjoiZjUyMzQ4MzYtYzkxNi00NWIwLWJhZjYtM2MwNjhjNjU5ZWJlIiwiZXhwIjoxNjkzMzQzODAxLCJpc3MiOiJEaW5uZXIiLCJhdWQiOiJEaW5uZXIifQ.4aZEfLxQwchJL2O4h_dKbDpIoH5IMW7if5DBUfAz9M8